INSERT INTO countries (name, country_id)
VALUES ("Afghanistan", "AF"),
("Albania", "AL"),
("Algeria", "DZ"),
("American Samoa", "AS"),
("Andorra", "AD"),
("Angola", "AO"),
("Anguilla", "AI"),
("Antarctica", "AQ"),
("Antigua and Barbuda", "AG"),
("Argentina", "AR"),
("Armenia", "AM"),
("Aruba", "AW"),
("Australia", "AU"),
("Austria", "AT"),
("Azerbaijan", "AZ"),
("Bahamas", "BS"),
("Bahrain", "BH"),
("Bangladesh", "BD"),
("Barbados", "BB"),
("Belarus", "BY"),
("Belgium", "BE"),
("Belize", "BZ"),
("Benin", "BJ"),
("Bermuda", "BM"),
("Bhutan", "BT"),
("Bolivia", "BO"),
("Botswana", "BW"),
("Bouvet Island", "BV"),
("Brazil", "BR"),
("Brunei Darussalam", "BN"),
("Bulgaria", "BG"),
("Burkina Faso", "BF"),
("Burundi", "BI"),
("Cambodia", "KH"),
("Cameroon", "CM"),
("Canada", "CA"),
("Cayman Islands", "KY"),
("Central African Republic", "CF"),
("Chad", "TD"),
("Chile", "CL"),
("China", "CN"),
("Christmas Island", "CX"),
("Colombia", "CO"),
("Congo", "CG"),
("Costa Rica", "CR"),
("Croatia", "HR"),
("Cuba", "CU"),
("Curaçao", "CW"),
("Cyprus", "CY"),
("Czechia", "CZ"),
("Denmark", "DK"),
("Djibouti", "DJ"),
("Dominica", "DM"),
("Dominican Republic", "DO"),
("Ecuador", "EC"),
("Egypt", "EG"),
("El Salvador", "SV"),
("Equatorial Guinea", "GQ"),
("Eritrea", "ER"),
("Estonia", "EE"),
("Eswatini", "SZ"),
("Ethiopia", "ET"),
("Fiji", "FJ"),
("Finland", "FI"),
("France", "FR"),
("French Guiana", "GF"),
("French Polynesia", "PF"),
("Gabon", "GA"),
("Gambia", "GM"),
("Georgia", "GE"),
("Germany", "DE"),
("Ghana", "GH"),
("Gibraltar", "GI"),
("Greece", "GR"),
("Greenland", "GL"),
("Grenada", "GD"),
("Guadeloupe", "GP"),
("Guam", "GU"),
("Guatemala", "GT"),
("Guernsey", "GG"),
("Guinea", "GN"),
("Guyana", "GY"),
("Haiti", "HT"),
("Honduras", "HN"),
("Hong Kong", "HK"),
("Hungary", "HU"),
("Iceland", "IS"),
("India", "IN"),
("Indonesia", "ID"),
("Iran", "IR"),
("Iraq", "IQ"),
("Ireland", "IE"),
("Isle of Man", "IM"),
("Israel", "IL"),
("Italy", "IT"),
("Jamaica", "JM"),
("Japan", "JP"),
("Jersey", "JE"),
("Jordan", "JO"),
("Kazakhstan", "KZ"),
("Kenya", "KE"),
("Kiribati", "KI"),
("North Korea", "KP"),
("Korea", "KR"),
("Kuwait", "KW"),
("Kyrgyzstan", "KG"),
("Latvia", "LV"),
("Lebanon", "LB"),
("Lesotho", "LS"),
("Liberia", "LR"),
("Libya", "LY"),
("Liechtenstein", "LI"),
("Lithuania", "LT"),
("Luxembourg", "LU"),
("Macao", "MO"),
("Madagascar", "MG"),
("Malawi", "MW"),
("Malaysia", "MY"),
("Maldives", "MV"),
("Mali", "ML"),
("Malta", "MT"),
("Martinique", "MQ"),
("Mauritania", "MR"),
("Mauritius", "MU"),
("Mayotte", "YT"),
("Mexico", "MX"),
("Moldova", "MD"),
("Monaco", "MC"),
("Mongolia", "MN"),
("Montenegro", "ME"),
("Montserrat", "MS"),
("Morocco", "MA"),
("Mozambique", "MZ"),
("Myanmar", "MM"),
("Namibia", "NA"),
("Nauru", "NR"),
("Nepal", "NP"),
("Netherlands", "NL"),
("New Caledonia", "NC"),
("New Zealand", "NZ"),
("Nicaragua", "NI"),
("Niger", "NE"),
("Nigeria", "NG"),
("Niue", "NU"),
("Norway", "NO"),
("Oman", "OM"),
("Pakistan", "PK"),
("Palau", "PW"),
("Palestine", "PS"),
("Panama", "PA"),
("Papua New Guinea", "PG"),
("Paraguay", "PY"),
("Peru", "PE"),
("Philippines", "PH"),
("Pitcairn", "PN"),
("Poland", "PL"),
("Portugal", "PT"),
("Puerto Rico", "PR"),
("Qatar", "QA"),
("Republic of North Macedonia", "MK"),
("Romania", "RO"),
("Russia", "RU"),
("Rwanda", "RW"),
("Réunion", "RE"),
("Samoa", "WS"),
("San Marino", "SM"),
("Sao Tome and Principe", "ST"),
("Saudi Arabia", "SA"),
("Senegal", "SN"),
("Serbia", "RS"),
("Seychelles", "SC"),
("Sierra Leone", "SL"),
("Singapore", "SG"),
("Slovakia", "SK"),
("Slovenia", "SI"),
("Solomon Islands", "SB"),
("Somalia", "SO"),
("South Africa", "ZA"),
("South Sudan", "SS"),
("Spain", "ES"),
("Sri Lanka", "LK"),
("Sudan", "SD"),
("Suriname", "SR"),
("Sweden", "SE"),
("Switzerland", "CH"),
("Syrian Arab Republic", "SY"),
("Taiwan", "TW"),
("Tajikistan", "TJ"),
("Tanzania", "TZ"),
("Thailand", "TH"),
("Togo", "TG"),
("Tokelau", "TK"),
("Tonga", "TO"),
("Trinidad and Tobago", "TT"),
("Tunisia", "TN"),
("Turkey", "TR"),
("Turkmenistan", "TM"),
("Tuvalu", "TV"),
("Uganda", "UG"),
("Ukraine", "UA"),
("United Arab Emirates", "AE"),
("Great Britain", "GB"),
("United States", "US"),
("Uruguay", "UY"),
("Uzbekistan", "UZ"),
("Vanuatu", "VU"),
("Venezuela", "VE"),
("Vietnam", "VN"),
("Yemen", "YE"),
("Zambia", "ZM"),
("Zimbabwe", "ZW");